### ISSUE TITLE
ts files

### ISSUE THREAD

**Issue by fpgasdr** [drmpeg/gr-dvbt2#1]
Hello,
I'm new with this tool but looks amazing.

the first problem are the .ts input files I can't find because are not included and the ftp link from bbc only have inside .txt files.

any help about how to generate the .ts files from the txt test point 01 witch should be the ts input files.

Thanks,
regards.

**Comment by drmpeg** [comment]
Here's a little utility I used to convert the BBC text files.

http://www.w6rz.net/bbcconvert.c

The usage would be (for example):

./bbcconvert 0 VV009-4KFFT-TP01_CSP.txt vv009-4kfft.ts

mode 0 is for byte data, mode 1 is for bit data and mode 2 is for floating point data.

Floating point data will not match perfectly. For that, I have another little utility that compares floating point files with an error tolerance.

http://www.w6rz.net/difffloat.c

Note that gr-dvbt2 is now part of GNU Radio itself in the gr-dtv component. Most of the changes are for MacOS compile compatibility. Functionality is identical, but not all of the test flow graphs are included.

**Comment by fpgasdr** [comment]
Thanks a lot for the help.
