### ISSUE TITLE
t2mi file input

### ISSUE THREAD

**Issue by julianmartinenzsou** [drmpeg/gr-dvbt2#2]
Hello again,

I have seen there is the option to set as input in the CSP Matlab enviroment a t2mi file as input and would like to know if it could be possible to set as input in this enviroment the same file to compare testpoints.

Thanks,
regards.

**Comment by drmpeg** [comment]
Sorry, there's no support for T2-MI input. Also, there's no support for multiple PLP streams. T2Lite streams are supported, but to get bit perfect results you have to make some minor source code changes and ignore the FEF portion.
