### ISSUE TITLE
dvbt2-blade.py Attribute error

### ISSUE THREAD

**Issue by ykhaled** [drmpeg/gr-dvbt2#3]
Unable to run dvbt2-blade.py. The following error returned;

```
Traceback (most recent call last):
  File "./dvbt2-blade.py", line 165, in <module>
    main(sys.argv[1:])
  File "./dvbt2-blade.py", line 37, in main
    version = dvbt2.VERSION_111
AttributeError: 'module' object has no attribute 'VERSION_111'
```

Re-produce: 
`./dvbt2-blade.py adv4k64qam.ts`

OS: Ubuntu 16.04.2
SDR: BladeRF
GNURadio: From Ubuntu package 3.7.9
Note: Did not attempt to "make install" gr-dvbt2 as I believe is now part of GNURadio?

**Comment by drmpeg** [comment]
Here's an updated version. https://github.com/drmpeg/dtv-utils/blob/master/dvbt2-blade.py
