### ISSUE TITLE
generating testpoint files

### ISSUE THREAD

**Issue by fpgasdr** [drmpeg/gr-dvbt2#4]
hello ron,
I'm running the VV009-4KFFT example to be able to generate some testpoints and for some reason the complex values acquired in some points (complex value points) don't give me the same values like the BBC reference streams and would like to see if there is any special consideration in order to have this values in the same way the reference streams from BBC are done.

Thanks,
regards.

P.D. just for clarify, in GRC I put file sinks connected to the output of the block i want to receive values and with the Matlab functions from GNUradio to convert to data this files I have the data in Matlab.
I use also to convert VV functions in the CSP to acquire the data from txt files from reference streams.

**Comment by drmpeg** [comment]
The floating point values aren't going to match exactly.  I have a tool that compares two floating point files and prints values that are above a difference threshold (0.000001).

http://www.w6rz.net/difffloat.c

Here's what I get with VV009-4KFFT:

```
$ ./difffloat vv.cfile vv009-4kfft.cfile
@0000055997, +1.735065e+00, +1.735066e+00, -1.072884e-06
@0000058089, -2.467487e+00, -2.467488e+00, +1.192093e-06
@0000157017, +1.249186e+00, +1.249187e+00, -1.072884e-06
@0000163364, +2.851902e+00, +2.851904e+00, -1.430511e-06
@0000176622, +2.269220e+00, +2.269221e+00, -1.192093e-06
@0000238306, -1.982250e+00, -1.982251e+00, +1.072884e-06
@0000260203, -2.128785e+00, -2.128786e+00, +1.192093e-06
@0000426633, -1.833872e+00, -1.833873e+00, +1.072884e-06
@0000434825, -1.833872e+00, -1.833873e+00, +1.072884e-06
@0000449770, +1.958865e+00, +1.958866e+00, -1.072884e-06
@0000459196, +2.152774e+00, +2.152775e+00, -1.192093e-06
@0000497702, +1.853579e+00, +1.853580e+00, -1.072884e-06
@0000501852, -1.738969e+00, -1.738970e+00, +1.192093e-06
@0000503516, -2.859534e+00, -2.859535e+00, +1.192093e-06
@0000518946, +2.281933e+00, +2.281934e+00, -1.192093e-06
@0000572132, -1.878176e+00, -1.878177e+00, +1.072884e-06
@0000617150, -1.882686e+00, -1.882687e+00, +1.072884e-06
@0000631527, +2.406011e+00, +2.406012e+00, -1.192093e-06
@0000680421, -1.554937e+00, -1.554938e+00, +1.072884e-06
@0000708498, +2.312456e+00, +2.312457e+00, -1.192093e-06
@0000797490, +2.222041e+00, +2.222042e+00, -1.192093e-06
@0000805521, +1.879586e+00, +1.879587e+00, -1.192093e-06
@0000813677, +1.841566e+00, +1.841567e+00, -1.072884e-06
@0000854852, +2.304926e+00, +2.304927e+00, -1.192093e-06
@0000863614, +2.329677e+00, +2.329678e+00, -1.192093e-06
```
So it's "floating point perfect".

**Comment by fpgasdr** [comment]
thanks for reply sorry for be late,
my case the differences are higher and I discover what happens to me:

The input ts file values adv4k64qam.ts differs from the testpoint 01 of VV009-4KFFT_CSP downloaded from ftp://ftp.kw.bbc.co.uk/t2refs/streams/  supposed to be the ts input file because there is only one PLP.

while in the data from VV I have ts data, the input ts file adv4k64qam.ts is almost null packets. 

is this correct or I'm missing something?.

I downloaded the ts files from http://www.w6rz.net/vv009-4kfft.ts so I supppose it's the correct file.

thanks,
regards.

**Comment by drmpeg** [comment]
The test file vv009-4kfft.ts has nothing to do with verification. It's a file with video to be used for demonstration purposes. You can play it in VLC. It is identical to adv4k64qam.ts.

Go back and read issue 1 (that you submitted) for instructions.

https://github.com/drmpeg/gr-dvbt2/issues/1

**Comment by fpgasdr** [comment]
Hi @drmpeg,

Thanks for the response and the help, now I'm able to generate the testpoints and they are equal(except for the resolution issue about e1-6).

Regards.
