### ISSUE TITLE
Build Error at `make`

### ISSUE THREAD

**Issue by Andreas237** [drmpeg/gr-dvbt2#8]
`make` and `sudo make` yields *error: lvalue required as left operand of assignment*.  See attached file for full output.
[build_errors.txt](https://github.com/drmpeg/gr-dvbt2/files/4327371/build_errors.txt)

**Comment by drmpeg** [comment]
This repository is pretty much deprecated (in fact, I'm going to mark it read-only after this conversation). It was moved into the GNU Radio mainline back in 2015 (as part of the gr-dtv component). Since then, there have been many performance enhancements. You should be using that instead.
